name: CDK Pipeline

on:
  pull_request:
    types: 
      - opened
    # paths:
    #   - 'cdk/**'
    branches:
      - 'main'
  push:
    # paths:
    #   - 'cdk/**'
    branches:
      - 'main'
jobs:
  build-dev:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Install Dependencies
        run: |
          npm install -g aws-cdk
        if: success()

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.TEST_SECRET }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
          aws configure set default.region us-east-1  # Change to your region
        if: success()

      - name: cdk synth
        run: cdk synth
        if: success()

      - name: cdk diff
        run: cdk diff
        if: success()

  deploy-to-dev:
    needs: build-dev
    runs-on: ubuntu-latest
    environment: dev
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'
        
      - name: Install Dependencies
        run: |
          npm install -g aws-cdk

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
          aws configure set default.region us-east-1  # Change to your region
      
      - name: cdk deploy
        run: |
          cdk deploy
        if: success()

  build-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Install Dependencies
        run: |
          npm install -g aws-cdk
        if: success()

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.TEST_SECRET }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
          aws configure set default.region us-east-1  # Change to your region
        if: success()

      - name: cdk synth
        run: cdk synth
        if: success()

      - name: cdk diff
        run: cdk diff
        if: success()

  deploy-to-prod:
    needs: [ build-prod, deploy-to-dev ]
    runs-on: ubuntu-latest
    environment: prod
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'
        
      - name: Install Dependencies
        run: |
          npm install -g aws-cdk

          
      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
          aws configure set default.region us-east-1  # Change to your region

      - name: cdk synth
        run: cdk synth
        if: success()

      - name: cdk diff
        run: cdk diff
        if: success()
      
      - name: cdk deploy
        run: |
          cd ./
          cdk deploy
        if: success()